### ISSUE TITLE
How to express an object whose keys are ids?

### ISSUE THREAD

**Issue by anentropic** [apiaryio/mson#68]
I can't see how to specify:

- an object with variable keys
- the type of an object keys (can only name a key, giving it a string type)

I want to describe a response that looks like

```
{
    1: (UserObject),
    2: (UserObject),
}
```

etc, where the keys are ids

**Comment by anentropic** [comment]
ok, I found this syntax:

```
    + Attributes (object)
        + *123* (PublicUser, optional) - example user, id=123
        + *456* (PublicUser, optional) - example user, id=456
```

this seems to express what I want. The only issue I have is that `drafter` parses this as:

```
                                  -
                                    element: "member"
                                    meta:
                                      description: "example user, id=123"
                                    attributes:
                                      typeAttributes:
                                        - "optional"
                                    content:
                                      key:
                                        element: "string"
                                        attributes:
                                          variable: true
                                        content: "123"
                                      value:
                                        element: "PublicUser"
```

How do I tell it that `*123*` represents a `number` variable rather than `string` ?
